version: '3'
services:
  ssh:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volumes/root:/root/host
    environment:
      - VNC_PASSWORD=CHANGEME!
    ports:
      # You can use any port, but 443 is normally allowed through corp firewalls.
      - "443:22"
      # Free utility port for metasploit etc.
      - "666:666"
      # Uncomment to expose VNC (bad idea)
      #- "80:80"
      #- "5900:5900"


